src/main/java/evento/faces/mngbeans/BoletoBean.java
package evento.faces.mngbeans;

import evento.persistence.controller.InscricaoJpaController;
import evento.persistence.entity.Inscricao;
import evento.persistence.entity.InscricaoMinicurso;
import evento.persistence.entity.InscricaoPagamento;
import evento.persistence.entity.InscricaoVisita;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.ResourceBundle;
import java.util.TimeZone;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import utfpr.faces.support.RequestBean;
import utfpr.util.DVModulo10;
import utfpr.util.DVModulo11;

@ManagedBean
@RequestScoped
public class BoletoBean extends RequestBean {

    private Integer numeroInscricao;
    private Integer numeroPagamento;
    private InscricaoJpaController inscricaoJpaController;
    private boolean avulso;
    private Date dataDocumento = new Date();
    private Date dataProcessamento = dataDocumento;
    private final DVModulo11 dvMod11 = new DVModulo11();
    private final DVModulo10 dvMod10 = new DVModulo10();
    private static final ResourceBundle paramBoleto = ResourceBundle.getBundle("cema.boleto.campos");
    private static final ResourceBundle config = ResourceBundle.getBundle("cema.config.interface");
    private static final Calendar dataBaseVencimento = new GregorianCalendar(1997, Calendar.OCTOBER, 7);
    private List<String> instrucoes;

    public BoletoBean() {
    }

    public BoletoBean(Integer numeroInscricao, Integer numeroPagamento) {
        this.numeroInscricao = numeroInscricao;
        this.numeroPagamento = numeroPagamento;
    }

    public Integer getNumeroInscricao() {
        return numeroInscricao;
    }

    public void setNumeroInscricao(Integer numeroInscricao) {
        this.numeroInscricao = numeroInscricao;
    }

    public Integer getNumeroPagamento() {
        return numeroPagamento;
    }

    public void setNumeroPagamento(Integer numeroPagamento) {
        this.numeroPagamento = numeroPagamento;
    }

    private Inscricao getInscricao(boolean lazy) {
        inscricaoJpaController = new InscricaoJpaController(lazy);
        return numeroInscricao == null ? null : inscricaoJpaController.findByNumero(numeroInscricao);
    }

    public Inscricao getInscricao() {
        return getInscricao(false);
    }

    public Inscricao getInscricaoLazy() {
        return getInscricao(true);
    }

    private void closeInscricaoJpaController() {
        inscricaoJpaController.close();
    }

    public int getPessoaAvulso() {
        return (int) ((System.currentTimeMillis() / 100) % 100000000);
    }

    public boolean isAvulso() {
        return avulso;
    }

    public void setAvulso(boolean avulso) {
        this.avulso = avulso;
    }

    public String getNomeSacado() {
        return getInscricao().getNome();
    }

    public String getParam(String key) {
        return paramBoleto.getString(key);
    }

    public Integer getParamAsInt(String key) {
        String param = getParam(key);
        return param == null ? null : Integer.valueOf(param);
    }

    public Long getParamAsLong(String key) {
        String param = getParam(key);
        return param == null ? null : Long.valueOf(param);
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando {@code pattern} como
     * formato de entrada. O padrão utilizado deve estar de acordo com a
     * especificação da classe {@code java.text.SimpleDateFormat}.
     *
     * @param key A chave identificadora do parâmetro
     * @param pattern O formato do valor de entrada
     * @return A data
     */
    public Date getParamAsDate(String key, String pattern) {
        String param = getParam(key);
        if (param == null) {
            return null;
        }
        final SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        try {
            return sdf.parse(param);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando o formato canônico
     * (yyyy-MM-dd).
     *
     * @param key A chave identificadora do parâmetro
     * @return A data
     */
    public Date getParamAsDate(String key) {
        return getParamAsDate(key, "yyyy-MM-dd");
    }

    public String getConfig(String key) {
        return config.getString(key);
    }

    public Integer getConfigAsInt(String key) {
        String param = getConfig(key);
        return param == null ? null : Integer.valueOf(param);
    }

    public Long getConfigAsLong(String key) {
        String param = getConfig(key);
        return param == null ? null : Long.valueOf(param);
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando {@code pattern} como
     * formato de entrada. O padrão utilizado deve estar de acordo com a
     * especificação da classe {@code java.text.SimpleDateFormat}.
     *
     * @param key A chave identificadora do parâmetro
     * @param pattern O formato do valor de entrada
     * @return A data
     */
    public Date getConfigAsDate(String key, String pattern) {
        String param = getConfig(key);
        if (param == null) {
            return null;
        }
        final SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        try {
            return sdf.parse(param);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando o formato canônico
     * (yyyy-MM-dd).
     *
     * @param key A chave identificadora do parâmetro
     * @return A data
     */
    public Date getConfigAsDate(String key) {
        return getConfigAsDate(key, "yyyy-MM-dd");
    }

    public Date getDataDocumento() {
        return dataDocumento;
    }

    public Date getDataProcessamento() {
        return dataProcessamento;
    }

    public long getNumeroDocumento() {
        InscricaoPagamento pgto = getInscricaoLazy().getInscricaoPagamentoList().get(0);
        Integer idEvento = getParamAsInt("boleto.evento.id");
        long numDoc =  idEvento * 10000000000000L + pgto.getNumeroDocumento() * 100000L
                + pgto.getInscricao().getNumero();
        closeInscricaoJpaController();
        return numDoc;
    }

    public long getNossoNumero() {
        return 24000000000000000L + getNumeroDocumento();
    }

    public Double getValorDocumento() {
        Double valor = getInscricaoLazy().getInscricaoPagamentoList()
                .get(0).getValorDocumento();
        closeInscricaoJpaController();
        return valor;
    }

    public long getValorDoctoAsLong() {
        return Math.round(getValorDocumento() * 100);
    }

    /**
     * Retorna o dígito verificador do nosso número.
     *
     * @return O DV do nosso número
     */
    public int getDvNossoNumero() {
        dvMod11.setValor(getNossoNumero());
        return dvMod11.getDigito();
    }

    public Date getDataVencimento() {
        Date dataVencto = getInscricaoLazy().getInscricaoPagamentoList()
                .get(0).getDataVencimento();
        closeInscricaoJpaController();
        return dataVencto;
    }

    public int getDvCampoLivre() {
        String nn = String.format("%017d", getNossoNumero());
        String cl = String.format("%06d%01d%3s%1d%3s%1d%9s",
                getParamAsInt("boleto.cedente.codigo"),
                getParamAsInt("boleto.cedente.dv"),
                nn.substring(2, 5),
                getParamAsInt("boleto.cobranca.tipo"),
                nn.substring(5, 8),
                getParamAsInt("boleto.cobranca.emissao"),
                nn.substring(8, 17));
        dvMod11.setValor(cl);
        return dvMod11.getDigito();
    }
    
    public int getFatorVencimento() {
        Date venc = getDataVencimento();
        long difMillis = venc.getTime() - dataBaseVencimento.getTimeInMillis();
        long difDias = difMillis / (24 * 60 * 60 * 1000L);
        return (int) difDias;
    }

    public String getCampoLivre() {
        String nn = String.format("%017d", getNossoNumero());
        return String.format("%06d%01d%3s%1d%3s%1d%9s%1d",
                getParamAsInt("boleto.cedente.codigo"),
                getParamAsInt("boleto.cedente.dv"),
                nn.substring(2, 5),
                getParamAsInt("boleto.cobranca.tipo"),
                nn.substring(5, 8),
                getParamAsInt("boleto.cobranca.emissao"),
                nn.substring(8, 17),
                getDvCampoLivre());
    }

    public int getDvCodigoBarras() {
        String base = String.format("%03d%1d%04d%010d%25s",
                getParamAsInt("boleto.banco.codigo"),
                getParamAsInt("boleto.moeda.codigo"),
                getFatorVencimento(),
                getValorDoctoAsLong(),
                getCampoLivre());
        dvMod11.setValor(base);
        dvMod11.setVariante(DVModulo11.DVM11_BARCODE);
        int dv = dvMod11.getDigito();
        dvMod11.setVariante(DVModulo11.DVM11_NORMAL);
        return dv;
    }

    public String getCodigoBarras() {
        return String.format("%03d%1d%1d%04d%010d%25s",
                getParamAsInt("boleto.banco.codigo"),
                getParamAsInt("boleto.moeda.codigo"),
                getDvCodigoBarras(),
                getFatorVencimento(),
                getValorDoctoAsLong(),
                getCampoLivre());
    }

    public String getLinhaDigitavel() {
        StringBuilder linha = new StringBuilder(54);
        String cb = getCodigoBarras();
        String base = cb.substring(0, 4) + cb.substring(19, 24);

src/main/java/evento/faces/mngbeans/ConsultaArtigosBean.java
package evento.faces.mngbeans;

import evento.persistence.controller.InscricaoJpaController;
import evento.persistence.entity.Inscricao;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import utfpr.faces.support.PageBean;

/**
 *
 * @author Wilson
 */
@ManagedBean
@RequestScoped
public class ConsultaArtigosBean extends  PageBean {
    private static final long serialVersionUID = 1L;
    DataModel<Inscricao> inscricoesDataModel;

    public ConsultaArtigosBean() {
    }

    public List<Inscricao> getInscricoes() {
        InscricaoJpaController ctl = new InscricaoJpaController();
        return ctl.findByArtigos();
    }
    
    public DataModel<Inscricao> getInscricoesDataModel() {
        if (inscricoesDataModel == null)
            inscricoesDataModel = new ListDataModel<>(getInscricoes());
        return inscricoesDataModel;
    }
    
}

src/main/webapp/admin/consulta-artigos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                xmlns:icecore="http://www.icefaces.org/icefaces/core"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="top"/>

    <ui:define name="formulario">
        <h:form>
            <p class="style2" align="center"><span class="style9">GERENCIAMENTO DE TRABALHOS SUBMETIDOS</span></p>
            <ace:dataTable value="#{consultaArtigosBean.inscricoesDataModel}"
                           var="inscricao" paginatorPosition="bottom" rows="20"
                           style="width: 755px">
           
                <ace:column headerText="+">
                    <ace:expansionToggler/>
                </ace:column>

                <ace:column headerText="Número" sortBy="#{inscricao.numero}">
                    <h:outputText value="#{inscricao.numero}">
                        <f:convertNumber pattern="00000"/>
                    </h:outputText>
                </ace:column>
                <ace:column headerText="Nome" sortBy="#{inscricao.nome}"
                            filterBy="#{inscricao.nome}" filterMatchMode="startsWith">
                    <h:outputText value="#{inscricao.nome}"/>
                </ace:column>
                <ace:column headerText="Situação" sortBy="#{inscricao.situacao.descricao}">
                    <f:facet name="header">
                        <h:graphicImage url="/imagens/tick_verde_10x10.png"/>
                    </f:facet>
                    <h:graphicImage url="#{inscricao.situacao.icone}" title="#{inscricao.situacao.descricao}"/>
                </ace:column>
                
                <ace:panelExpansion>
                    <h:panelGroup layout="block" style="text-align: left;">
                        <h:panelGroup layout="block" style="display: inline-block; vertical-align: top; text-align: left;">
                            <h:outputText value="Artigos:" style=""/>
                        </h:panelGroup>
                        <h:panelGroup layout="block" style="display: inline-block; text-align: left;">
                            <ui:repeat value="#{inscricao.artigoList}" var="artigo">
                                <p>
                                    <h:outputLink value="#{request.contextPath}/artigo/download" style="margin-left: 1em;">
                                        <h:outputText value="#{artigo.titulo}"/>
                                        <f:param name="a" value="#{artigo.artigoPK.autor}"/>
                                        <f:param name="s" value="#{artigo.artigoPK.seq}"/>
                                    </h:outputLink>
                                </p>
                            </ui:repeat>
                        </h:panelGroup>
                    </h:panelGroup>
                </ace:panelExpansion>
            </ace:dataTable>
            <h:messages/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/consulta-inscricoes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                xmlns:icecore="http://www.icefaces.org/icefaces/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="top"/>

    <ui:define name="formulario">
        <h:form>
            <p class="style2" align="center"><span class="style9">GERENCIAMENTO DE INSCRIÇÕES</span></p>
            <ace:dataTable value="#{consultaIncricoesBean.inscricoesDataModel}" paginator="true"
                           var="inscricao" paginatorPosition="bottom" rows="20"
                           style="width: 755px">
           
                <ace:column headerText="+">
                    <ace:expansionToggler/>
                </ace:column>

                <ace:column headerText="Número" sortBy="#{inscricao.numero}">
                    <h:outputText value="#{inscricao.numero}">
                        <f:convertNumber pattern="00000"/>
                    </h:outputText>
                </ace:column>
                <ace:column headerText="CPF" sortBy="#{inscricao.cpf}">
                    <h:outputText value="#{inscricao.cpf}">
                        <f:convertNumber pattern="00000000000"/>
                    </h:outputText>
                </ace:column>
                <ace:column headerText="Nome" sortBy="#{inscricao.nome}"
                            filterBy="#{inscricao.nome}" filterMatchMode="startsWith">
                    <h:outputText value="#{inscricao.nome}"/>
                </ace:column>
                <ace:column headerText="Situação" sortBy="#{inscricao.situacao.descricao}"
                            filterBy="#{inscricao.situacao.codigo}" filterMatchMode="exact"
                            filterOptions="#{consultaIncricoesBean.situacaoFilterOptions}">
                    <f:facet name="header">
                        <h:graphicImage url="/imagens/tick_verde_10x10.png"/>
                    </f:facet>
                    <h:graphicImage url="#{inscricao.situacao.icone}" title="#{inscricao.situacao.descricao}"/>
                </ace:column>
                
                <ace:panelExpansion>
                    <h:panelGroup layout="block" style="text-align: left">
                        <h:outputText value="#{inscricao.categoria.descricao}"/><br/>
                        <h:outputText value="#{inscricao.endereco}"/><br/>
                        <h:outputText value="#{inscricao.cep}"/>
                        <h:outputText value="#{inscricao.cidade}" style="margin-left: 1em"/>
                        <h:outputText value="#{inscricao.estado}" style="margin-left: 1em"/><br/>
                        <h:outputText value="#{inscricao.fone}"/>
                        <h:outputText value="#{inscricao.email}" style="margin-left: 1em"/><br/>
                        <h:outputFormat value="Vencimento: {0, date, dd/MM/yyyy}">
                            <f:param value="#{inscricao.inscricaoPagamentoList[0].dataVencimento}"/>
                        </h:outputFormat>
                        <h:outputLink value="#{application.contextPath}/boleto.xhtml" target="_blank"
                                      style="margin-left: 1em;">
                            Gerar boleto
                            <f:param name="ninsc" value="#{inscricao.numero}"/>
                            <f:param name="npgto" value="#{inscricao.inscricaoPagamentoList[0].numeroDocumento}"/>
                        </h:outputLink>
                        <h:panelGroup layout="block"  rendered="#{inscricao.situacao.codigo != 2}" style="text-align: right">
                            <h:commandButton value="Excluir inscrição"
                                             onclick="ice.ace.instance('#{excluirInscricaoDialog.clientId}').show(); return false;"/>
                        </h:panelGroup>
                        
                        <ace:confirmationDialog id="excluirInscricaoDialog" header="Excluir inscrição" binding="#{excluirInscricaoDialog}"
                                                position="center" modal="true" draggable="false" width="300"
                                                message="Confirma a exclusão da inscrição número #{inscricao.numero}?">
                            <h:panelGroup layout="block" style="text-align: center;">
                                <h:panelGroup layout="block">
                                    <h:outputText value="Esta operação não poderá ser desfeita!"/>
                                </h:panelGroup>
                                <h:panelGroup layout="block" style="margin: 0.5em 2em;">
                                    <h:commandButton value="Sim" action="#{consultaIncricoesBean.excluiInscricaoAction}"
                                                     onclick="ice.ace.instance('#{excluirInscricaoDialog.clientId}').hide();">
                                        <f:ajax execute="@this" render="@all"/>
                                    </h:commandButton>
                                    <h:commandButton value="Não" style="margin-left: 1em;"
                                                     onclick="ice.ace.instance('#{excluirInscricaoDialog.clientId}').hide();">
                                        <f:ajax execute="@this" render="@all"/>
                                    </h:commandButton>
                                </h:panelGroup>
                            </h:panelGroup>
                        </ace:confirmationDialog>
                        
                        <ace:confirmationDialog id="alteraVenctoDialog" header="Alterar vencimento" binding="#{alteraVenctoDialog}"
                                                position="center" modal="true" draggable="false" width="300"
                                                message="Confirma a alteração do vencimento da inscrição número #{inscricao.numero}?">
                            <h:panelGroup layout="block" style="text-align: center;">
                                <h:panelGroup layout="block" style="margin: 0.5em 2em;">
                                    <h:commandButton value="Sim" action="null"
                                                     onclick="ice.ace.instance('#{alteraVenctoDialog.clientId}').hide();">
                                        <f:ajax execute="@this" render="@all"/>
                                    </h:commandButton>
                                    <h:commandButton value="Não" style="margin-left: 1em;"
                                                     onclick="ice.ace.instance('#{alteraVenctoDialog.clientId}').hide();">
                                        <f:ajax execute="@this" render="@all"/>
                                    </h:commandButton>
                                </h:panelGroup>
                            </h:panelGroup>
                        </ace:confirmationDialog>
                        
                    </h:panelGroup>
                </ace:panelExpansion>
            </ace:dataTable>
            <h:messages/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/retorno-banco.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                xmlns:icecore="http://www.icefaces.org/icefaces/core"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="top"/>

    <ui:define name="formulario">
        <h:form>
            <p class="style2" align="center"><span class="style9">PROCESSAMENTO DE RETORNOS DE PAGAMENTOS DO BANCO</span></p>
            <h:panelGroup layout="block">
                <ace:fileEntry label="Retornos"
                               relativePath="/WEB-INF/cobranca/retornos/"
                               maxFileCount="10"
                               maxFileCountMessage="Máximo de 10 arquivos simultâneos"
                               fileEntryListener="#{retornoUploadBean.uploadListener}"
                               maxFileSize="102400"
                               maxFileSizeMessage="Tamanho do arquivo excede o máximo permitido"
                               maxTotalSize="1048576"
                               maxTotalSizeMessage="Tamanho total dos arquivos excede o máximo permitido"
                               required="true"
                               requiredMessage="Selecione arquivos para enviar"
                               useOriginalFilename="true"
                               useSessionSubdir="false"
                               autoUpload="false"
                               multiple="true"/>
            </h:panelGroup>
            <h:messages/>
        </h:form>
    </ui:define>
</ui:composition>