src/main/java/evento/faces/mngbeans/ApplicationBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package evento.faces.mngbeans;

import javax.faces.application.Application;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author Wilson
 */
@ManagedBean(eager=true)
@ApplicationScoped
public class ApplicationBean extends utfpr.faces.support.ApplicationBean {
    private static final long serialVersionUID = 1L;

    public ApplicationBean() {
    }
}

src/main/java/evento/faces/mngbeans/ArtigoUploadBean.java
package evento.faces.mngbeans;

import evento.persistence.controller.ArtigoJpaController;
import evento.persistence.controller.InscricaoJpaController;
import evento.persistence.entity.Artigo;
import evento.persistence.entity.ArtigoPK;
import evento.persistence.entity.Inscricao;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import org.apache.commons.codec.digest.DigestUtils;
import org.icefaces.ace.component.fileentry.FileEntry;
import org.icefaces.ace.component.fileentry.FileEntryEvent;
import org.icefaces.ace.component.fileentry.FileEntryResults;
import org.icefaces.ace.component.fileentry.FileEntryStatuses;
import utfpr.faces.support.PageBean;

/**
 *
 * @author Wilson
 */
@ManagedBean
@ViewScoped
public class ArtigoUploadBean extends PageBean {
    
    public static final String MIME_VALIDO = "application/pdf";

    private Inscricao inscricao;
    private Artigo artigo = new Artigo();
    private Long cpf;
    private String fone;
    private String email;

    /**
     * Creates a new instance of ArtigoUploadBean
     */
    public ArtigoUploadBean() {
    }

    public Long getCpf() {
        return cpf;
    }

    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    public String getFone() {
        return fone;
    }

    public void setFone(String fone) {
        this.fone = fone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Inscricao getInscricao() {
        if (cpf != null && inscricao == null) {
            InscricaoJpaController ctl = new InscricaoJpaController();
            inscricao = ctl.findByCPF(cpf);
        }
        return inscricao;
    }

    public Artigo getArtigo() {
        return artigo;
    }

    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    
    private boolean validaSituacao() {
        boolean valido = inscricao.getSituacao().equals(InscricaoJpaController.SITUACAO_CONFIRMADO); 
        if (!valido) {
            error("Sua inscrição ainda não foi confirmada: submissão de trabalhos indisponível");
        }
        return valido;
    }
    
    public boolean isMaxArtigosSubmetidos() {
        return inscricao.getArtigoList().size() >= 1;
    }
    
    public boolean isInscricaoConfirmada() {
        return getInscricao().getSituacao().getCodigo()
            .equals(InscricaoJpaController.SITUACAO_CONFIRMADO.getCodigo());
    }
    
    private boolean validaMaxArtigos() {
        boolean valido = !isMaxArtigosSubmetidos();
        if (!valido) {
            error("Você já submeteu o número máximo de trabalhos permitidos");
        }
        return valido;
    }
    
    private boolean validaInscricao() {
        boolean valida = false;
        try {
            inscricao = getInscricao();
            valida = inscricao != null && inscricao.getFone().equals(fone)
                        && inscricao.getEmail().equalsIgnoreCase(email);
            if (!valida) {
                error("Inscrição não localizada. Por favor, certifique-se de "
                        + "que os dados informados estão corretos.");
                inscricao = null;
            }
        } catch (Throwable t) {
            inscricao = null;
            log("validaInscricao", t);
            throw t;
        }
        return valida;
    }
    
    private boolean validaTipoArquivo(FileEntryResults.FileInfo fileInfo) {
        // TODO: Verificar o conteúdo do arquivo para assegurar que seja
        //       realmente um PDF (arquivo começa com o string %PDF).
        //       De forma mais genérica, implementar verificação de outros
        //       tipos de arquivos.
        //       (*) Teste do mime type não se mostrou confiável pois depende
        //           do envio correto do Content-Type pelo navegador
        boolean valido = fileInfo.getFileName().toLowerCase().endsWith(".pdf");
        if (!valido) {
            fileInfo.updateStatus(FileEntryStatuses.INVALID, true);
        }
        return valido;
    }

    private boolean validaSubmissao(FileEntryResults.FileInfo fileInfo) {
        return validaTipoArquivo(fileInfo);
    }
    
    private void resetUpload() {
        artigo.setTitulo(null);
        artigo.setResumo(null);
        inscricao = null;
    }
    
    public String getArtigoHash() {
        String base = String.format("%011d%s", cpf,
                getExternalContext().getSessionId(false));
        return DigestUtils.sha1Hex(base);
    }
    
    private void adicionaArtigo(FileEntryResults.FileInfo info) {
        ArtigoJpaController ctl = new ArtigoJpaController();
        artigo.setArtigoPK(new ArtigoPK(inscricao.getNumero(), inscricao.getArtigoList().size()+1));
        artigo.setInscricao(inscricao);
        artigo.setArquivo(info.getFileName());
        ctl.persist(artigo);
        inscricao = ctl.getEntityManager().merge(inscricao);
    }
    
    public String uploadListener(FileEntryEvent event) {
        Date agora = new Date();
        FileEntry fe = (FileEntry) event.getComponent();
        FileEntryResults results = fe.getResults();
        List<FileEntryResults.FileInfo> filesInfo = results.getFiles();
        for (FileEntryResults.FileInfo info : filesInfo) {
            if (validaSubmissao(info)) {
                adicionaArtigo(info);
            } else {
                error(String.format("Erro: '%s' não pode ser submetido", info.getFileName()));
            }
        }
        resetUpload();
        return null;
    }

    public void validaInscricaoAction() {
        boolean valido = validaInscricao() && validaSituacao() &&  validaMaxArtigos();
        if (valido) {
            artigo = new Artigo();
            artigo.setInscricao(inscricao);
        } else {
            inscricao = null;
        }
    }
    
    public void submeterTrabalhoAction() {
        
    }
}

src/main/java/evento/faces/mngbeans/BoletoBean.java
package evento.faces.mngbeans;

import evento.persistence.controller.InscricaoJpaController;
import evento.persistence.entity.Inscricao;
import evento.persistence.entity.InscricaoMinicurso;
import evento.persistence.entity.InscricaoPagamento;
import evento.persistence.entity.InscricaoVisita;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.ResourceBundle;
import java.util.TimeZone;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import utfpr.faces.support.RequestBean;
import utfpr.util.DVModulo10;
import utfpr.util.DVModulo11;

@ManagedBean
@RequestScoped
public class BoletoBean extends RequestBean {

    private Integer numeroInscricao;
    private Integer numeroPagamento;
    private InscricaoJpaController inscricaoJpaController;
    private boolean avulso;
    private Date dataDocumento = new Date();
    private Date dataProcessamento = dataDocumento;
    private final DVModulo11 dvMod11 = new DVModulo11();
    private final DVModulo10 dvMod10 = new DVModulo10();
    private static final ResourceBundle paramBoleto = ResourceBundle.getBundle("cema.boleto.campos");
    private static final ResourceBundle config = ResourceBundle.getBundle("cema.config.interface");
    private static final Calendar dataBaseVencimento = new GregorianCalendar(1997, Calendar.OCTOBER, 7);
    private List<String> instrucoes;

    public BoletoBean() {
    }

    public BoletoBean(Integer numeroInscricao, Integer numeroPagamento) {
        this.numeroInscricao = numeroInscricao;
        this.numeroPagamento = numeroPagamento;
    }

    public Integer getNumeroInscricao() {
        return numeroInscricao;
    }

    public void setNumeroInscricao(Integer numeroInscricao) {
        this.numeroInscricao = numeroInscricao;
    }

    public Integer getNumeroPagamento() {
        return numeroPagamento;
    }

    public void setNumeroPagamento(Integer numeroPagamento) {
        this.numeroPagamento = numeroPagamento;
    }

    private Inscricao getInscricao(boolean lazy) {
        inscricaoJpaController = new InscricaoJpaController(lazy);
        return numeroInscricao == null ? null : inscricaoJpaController.findByNumero(numeroInscricao);
    }

    public Inscricao getInscricao() {
        return getInscricao(false);
    }

    public Inscricao getInscricaoLazy() {
        return getInscricao(true);
    }

    private void closeInscricaoJpaController() {
        inscricaoJpaController.close();
    }

    public int getPessoaAvulso() {
        return (int) ((System.currentTimeMillis() / 100) % 100000000);
    }

    public boolean isAvulso() {
        return avulso;
    }

    public void setAvulso(boolean avulso) {
        this.avulso = avulso;
    }

    public String getNomeSacado() {
        return getInscricao().getNome();
    }

    public String getParam(String key) {
        return paramBoleto.getString(key);
    }

    public Integer getParamAsInt(String key) {
        String param = getParam(key);
        return param == null ? null : Integer.valueOf(param);
    }

    public Long getParamAsLong(String key) {
        String param = getParam(key);
        return param == null ? null : Long.valueOf(param);
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando {@code pattern} como
     * formato de entrada. O padrão utilizado deve estar de acordo com a
     * especificação da classe {@code java.text.SimpleDateFormat}.
     *
     * @param key A chave identificadora do parâmetro
     * @param pattern O formato do valor de entrada
     * @return A data
     */
    public Date getParamAsDate(String key, String pattern) {
        String param = getParam(key);
        if (param == null) {
            return null;
        }
        final SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        try {
            return sdf.parse(param);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando o formato canônico
     * (yyyy-MM-dd).
     *
     * @param key A chave identificadora do parâmetro
     * @return A data
     */
    public Date getParamAsDate(String key) {
        return getParamAsDate(key, "yyyy-MM-dd");
    }

    public String getConfig(String key) {
        return config.getString(key);
    }

    public Integer getConfigAsInt(String key) {
        String param = getConfig(key);
        return param == null ? null : Integer.valueOf(param);
    }

    public Long getConfigAsLong(String key) {
        String param = getConfig(key);
        return param == null ? null : Long.valueOf(param);
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando {@code pattern} como
     * formato de entrada. O padrão utilizado deve estar de acordo com a
     * especificação da classe {@code java.text.SimpleDateFormat}.
     *
     * @param key A chave identificadora do parâmetro
     * @param pattern O formato do valor de entrada
     * @return A data
     */
    public Date getConfigAsDate(String key, String pattern) {
        String param = getConfig(key);
        if (param == null) {
            return null;
        }
        final SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        try {
            return sdf.parse(param);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Retorna uma parâmetro do arquivo de recursos usando o formato canônico
     * (yyyy-MM-dd).
     *
     * @param key A chave identificadora do parâmetro
     * @return A data
     */
    public Date getConfigAsDate(String key) {
        return getConfigAsDate(key, "yyyy-MM-dd");
    }

    public Date getDataDocumento() {
        return dataDocumento;
    }

    public Date getDataProcessamento() {
        return dataProcessamento;
    }

    public long getNumeroDocumento() {
        InscricaoPagamento pgto = getInscricaoLazy().getInscricaoPagamentoList().get(0);
        Integer idEvento = getParamAsInt("boleto.evento.id");
        long numDoc =  idEvento * 10000000000000L + pgto.getNumeroDocumento() * 100000L
                + pgto.getInscricao().getNumero();
        closeInscricaoJpaController();
        return numDoc;
    }

    public long getNossoNumero() {
        return 24000000000000000L + getNumeroDocumento();
    }

    public Double getValorDocumento() {
        Double valor = getInscricaoLazy().getInscricaoPagamentoList()
                .get(0).getValorDocumento();
        closeInscricaoJpaController();
        return valor;
    }

    public long getValorDoctoAsLong() {
        return Math.round(getValorDocumento() * 100);
    }

    /**
     * Retorna o dígito verificador do nosso número.
     *
     * @return O DV do nosso número
     */
    public int getDvNossoNumero() {
        dvMod11.setValor(getNossoNumero());
        return dvMod11.getDigito();
    }

    public Date getDataVencimento() {
        Date dataVencto = getInscricaoLazy().getInscricaoPagamentoList()
                .get(0).getDataVencimento();
        closeInscricaoJpaController();
        return dataVencto;
    }

    public int getDvCampoLivre() {
        String nn = String.format("%017d", getNossoNumero());
        String cl = String.format("%06d%01d%3s%1d%3s%1d%9s",
                getParamAsInt("boleto.cedente.codigo"),
                getParamAsInt("boleto.cedente.dv"),
                nn.substring(2, 5),
                getParamAsInt("boleto.cobranca.tipo"),
                nn.substring(5, 8),
                getParamAsInt("boleto.cobranca.emissao"),
                nn.substring(8, 17));
        dvMod11.setValor(cl);
        return dvMod11.getDigito();
    }
    
    public int getFatorVencimento() {
        Date venc = getDataVencimento();
        long difMillis = venc.getTime() - dataBaseVencimento.getTimeInMillis();
        long difDias = difMillis / (24 * 60 * 60 * 1000L);
        return (int) difDias;
    }

    public String getCampoLivre() {
        String nn = String.format("%017d", getNossoNumero());
        return String.format("%06d%01d%3s%1d%3s%1d%9s%1d",
                getParamAsInt("boleto.cedente.codigo"),
                getParamAsInt("boleto.cedente.dv"),
                nn.substring(2, 5),
                getParamAsInt("boleto.cobranca.tipo"),
                nn.substring(5, 8),
                getParamAsInt("boleto.cobranca.emissao"),
                nn.substring(8, 17),
                getDvCampoLivre());
    }

    public int getDvCodigoBarras() {
        String base = String.format("%03d%1d%04d%010d%25s",
                getParamAsInt("boleto.banco.codigo"),
                getParamAsInt("boleto.moeda.codigo"),
                getFatorVencimento(),
                getValorDoctoAsLong(),
                getCampoLivre());
        dvMod11.setValor(base);
        dvMod11.setVariante(DVModulo11.DVM11_BARCODE);
        int dv = dvMod11.getDigito();
        dvMod11.setVariante(DVModulo11.DVM11_NORMAL);
        return dv;
    }

    public String getCodigoBarras() {
        return String.format("%03d%1d%1d%04d%010d%25s",
                getParamAsInt("boleto.banco.codigo"),
                getParamAsInt("boleto.moeda.codigo"),
                getDvCodigoBarras(),
                getFatorVencimento(),
                getValorDoctoAsLong(),
                getCampoLivre());
    }

    public String getLinhaDigitavel() {
        StringBuilder linha = new StringBuilder(54);
        String cb = getCodigoBarras();
        String base = cb.substring(0, 4) + cb.substring(19, 24);

src/main/java/evento/faces/mngbeans/ConsultaArtigosBean.java
package evento.faces.mngbeans;

import evento.persistence.controller.InscricaoJpaController;
import evento.persistence.entity.Inscricao;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import utfpr.faces.support.PageBean;

/**
 *
 * @author Wilson
 */
@ManagedBean
@RequestScoped
public class ConsultaArtigosBean extends  PageBean {
    private static final long serialVersionUID = 1L;
    DataModel<Inscricao> inscricoesDataModel;

    public ConsultaArtigosBean() {
    }

    public List<Inscricao> getInscricoes() {
        InscricaoJpaController ctl = new InscricaoJpaController();
        return ctl.findByArtigos();
    }
    
    public DataModel<Inscricao> getInscricoesDataModel() {
        if (inscricoesDataModel == null)
            inscricoesDataModel = new ListDataModel<>(getInscricoes());
        return inscricoesDataModel;
    }
    
}

src/main/webapp/artigos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                xmlns:icecore="http://www.icefaces.org/icefaces/core"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="./WEB-INF/templates/layout.xhtml">

    <ui:define name="top"/>

    <ui:define name="formulario">
        <h:form>
            <p class="style2" align="center"><span class="style9">SUBMISSÃO DE TRABALHOS</span></p>
            <h:panelGroup layout="block">
                <p>
                    <ace:maskedEntry value="#{artigoUploadBean.cpf}"  mask="999999999-99" label="CPF" size="16" required="true"
                                     requiredIndicator="*" labelPosition="left" indicatorPosition="left" styleClass="evento-textentry-default"
                                     disabled="#{!empty artigoUploadBean.inscricao}">
                        <f:validator validatorId="CPFValidator"/>
                        <f:converter converterId="CPFConverter"/>
                    </ace:maskedEntry>
                </p>
                <p>
                    <ace:maskedEntry value="#{artigoUploadBean.fone}"  mask="(99) 99999999?9" label="Telefone para contato" size="18" required="true"
                                     requiredIndicator="*" labelPosition="left" indicatorPosition="left" styleClass="evento-textentry-default"
                                     disabled="#{!empty artigoUploadBean.inscricao}">
                        <f:converter converterId="PhoneConverter"/>
                    </ace:maskedEntry>
                </p>
                <p style="margin-top: 10px">
                    <ace:textEntry size="58" maxlength="100" value="#{artigoUploadBean.email}" label="E-mail" required="true" requiredIndicator="*"
                                   indicatorPosition="left" labelPosition="left" styleClass="evento-textentry-default"
                                   disabled="#{!empty artigoUploadBean.inscricao}"/>
                </p>
            </h:panelGroup>
            <h:panelGroup style="text-align: center; margin-top: 2em" layout="block" rendered="#{empty artigoUploadBean.inscricao}">
                <h:commandButton value="Validar inscrição" action="#{artigoUploadBean.validaInscricaoAction}"/>
            </h:panelGroup>
            <h:panelGroup layout="block" rendered="#{!empty artigoUploadBean.inscricao}" style="margin-top: 2em;">
                <h:panelGroup layout="block" rendered="#{artigoUploadBean.inscricaoConfirmada and !artigoUploadBean.maxArtigosSubmetidos}">
                    <h:panelGroup layout="block">
                        <p>
                            <ace:textEntry size="75" maxlength="200" value="#{artigoUploadBean.artigo.titulo}" label="Título" required="true" requiredIndicator="*"
                                           indicatorPosition="left" labelPosition="left" styleClass="evento-textentry-default"/>
                        </p>
                    </h:panelGroup>
                    <h:panelGroup layout="block">
                        <p>
                            <ace:textAreaEntry value="#{artigoUploadBean.artigo.resumo}" cols="72" rows="5"
                                               label="Resumo" required="true" requiredIndicator="*"
                                               indicatorPosition="left" labelPosition="left"/>
                        </p>
                    </h:panelGroup>
                    <ace:fileEntry id="fileUpload"
                                   label="Arquivo"
                                   relativePath="/WEB-INF/artigos/#{artigoUploadBean.inscricao.numero}"
                                   fileEntryListener="#{artigoUploadBean.uploadListener}"
                                   maxFileSize="1048576"
                                   maxFileSizeMessage="Tamanho do arquivo excede o máximo permitido"
                                   required="true"
                                   requiredMessage="Selecione um arquivo para enviar"
                                   useOriginalFilename="true"
                                   useSessionSubdir="false"
                                   autoUpload="false"
                                   multiple="false"/>
                    <h:panelGroup style="text-align: center; margin: 2em 0 2em 0" layout="block">
                        <h:commandButton value="Submeter trabalho" action="#{artigoUploadBean.submeterTrabalhoAction}">
                        </h:commandButton>
                    </h:panelGroup>
                </h:panelGroup>
                <p class="style2" style="text-align: center; margin-top: 2em;"><span class="style9">TRABALHOS SUBMETIDOS</span></p>
                <ace:dataTable value="#{artigoUploadBean.inscricao.artigoList}" var="artigo" style="width: 750px;"
                               emptyMessage="Nenhum trabalho submetido até o momento" >
                    <ace:column headerText="+" style="width: 20px;">
                        <ace:expansionToggler/>
                    </ace:column>
                    <ace:column headerText="Título" style="text-align: left;">
                        <h:outputLink value="#{request.contextPath}/artigo/download">
                            <h:outputText value="#{artigo.titulo}"/>
                            <f:param name="a" value="#{artigo.artigoPK.autor}"/>
                            <f:param name="s" value="#{artigo.artigoPK.seq}"/>
                            <f:param name="h" value="#{artigoUploadBean.artigoHash}"/>
                        </h:outputLink>
                    </ace:column>
                    <ace:column headerText="Data" style="width: 120px;">
                        <h:outputText value="#{artigo.dataSubmissao}">
                            <f:convertDateTime type="both" dateStyle="short" timeStyle="short"/>
                        </h:outputText>
                    </ace:column>
                    <ace:column headerText="Situação" style="width: 80px;">
                        <h:outputText value="#{artigo.situacao.descricao}"/>
                    </ace:column>

                    <ace:panelExpansion>
                        <h:panelGroup layout="block" style="text-align: left">
                            <h:outputText value="#{artigo.resumo}"/>
                        </h:panelGroup>
                    </ace:panelExpansion>
                </ace:dataTable>
            </h:panelGroup>
            <h:messages/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/consulta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                xmlns:icecore="http://www.icefaces.org/icefaces/core"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="./WEB-INF/templates/layout.xhtml">

    <ui:define name="top"/>

    <ui:define name="formulario">
        <h:form>
            <p class="style2" align="center"><span class="style9">CONSULTA INSCRIÇÃO</span></p>
            <h:panelGroup layout="block">
                <p>
                    <ace:maskedEntry value="#{consultaBean.cpf}"  mask="999999999-99" label="CPF" size="16" required="true"
                                     requiredIndicator="*" labelPosition="left" indicatorPosition="left" styleClass="evento-textentry-default">
                        <f:validator validatorId="CPFValidator"/>
                        <f:converter converterId="CPFConverter"/>
                    </ace:maskedEntry>
                </p>
                <p>
                    <ace:maskedEntry value="#{consultaBean.fone}"  mask="(99) 99999999?9" label="Telefone para contato" size="18" required="true"
                                     requiredIndicator="*" labelPosition="left" indicatorPosition="left" styleClass="evento-textentry-default">
                        <f:converter converterId="PhoneConverter"/>
                    </ace:maskedEntry>
                </p>
                <p style="margin-top: 10px">
                    <ace:textEntry size="58" maxlength="100" value="#{consultaBean.email}" label="E-mail" required="true" requiredIndicator="*"
                                   indicatorPosition="left" labelPosition="left" styleClass="evento-textentry-default"/>
                </p>
            </h:panelGroup>
            <h:panelGroup style="text-align: center; margin-top: 1em" layout="block">
                <h:commandButton value="Consultar" action="#{consultaBean.consultaAction}"/>
            </h:panelGroup>
            <h:panelGroup styleClass="cemaIceMsgsContainer" rendered="#{facesContext.messageList.size() > 0}" layout="block">
                <h:messages/>
            </h:panelGroup>
        </h:form>
    </ui:define>
</ui:composition>